# Generated by Django 5.2.1 on 2026-05-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='primary_color',
            field=models.CharField(default='#E8192C', help_text='Color principal en hex', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='secondary_color',
            field=models.CharField(default='#1a1a2e', help_text='Color secundario en hex', max_length=7),
        ),
    ]
